CREATE TABLE cel(
    id BIGSERIAL NOT NULL,
    eventtype VARCHAR(30) NOT NULL,
    eventtime TIMESTAMP WITH TIME ZONE NOT NULL,
    userdeftype VARCHAR(255) NOT NULL,
    cid_name VARCHAR(80) NOT NULL,
    cid_num VARCHAR(80) NOT NULL,
    cid_ani VARCHAR(80) NOT NULL,
    cid_rdnis VARCHAR(80) NOT NULL,
    cid_dnid VARCHAR(80) NOT NULL,
    exten VARCHAR(80) NOT NULL,
    context VARCHAR(80) NOT NULL,
    channame VARCHAR(80) NOT NULL,
    appname VARCHAR(80) NOT NULL,
    appdata VARCHAR(80) NOT NULL,
    amaflags INTEGER NOT NULL,
    accountcode VARCHAR(20) NOT NULL,
    peeraccount VARCHAR(20) NOT NULL,
    uniqueid VARCHAR(150) NOT NULL,
    linkedid VARCHAR(150) NOT NULL,
    peer VARCHAR(510) NOT NULL,
    extra TEXT NOT NULL,
    CONSTRAINT asterisk_cel_id_pk PRIMARY KEY (id)
) WITH (OIDS=FALSE);