CREATE TABLE cdr(
    id BIGSERIAL NOT NULL,
    "record" VARCHAR(150) NOT NULL,
    linkedid VARCHAR(150) NOT NULL,
    "sequence" INTEGER NOT NULL,
    clid VARCHAR(80) NOT NULL,
    src VARCHAR(80) NOT NULL,
    dst VARCHAR(80) NOT NULL,
    dcontext VARCHAR(80) NOT NULL,
    channel VARCHAR(80) NOT NULL,
    dstchannel VARCHAR(80),
    lastapp VARCHAR(80) NOT NULL,
    lastdata VARCHAR(255),
    calldate TIMESTAMP WITH TIME ZONE NOT NULL,
    answer TIMESTAMP WITH TIME ZONE,
    callend TIMESTAMP WITH TIME ZONE NOT NULL,
    duration REAL,
    billsec REAL,
    disposition VARCHAR(45) NOT NULL,
    amaflags INTEGER NOT NULL,
    accountcode VARCHAR(20),
    peeraccount VARCHAR(20),
    recfile VARCHAR(255),
    CONSTRAINT asterisk_cdr_id_pk PRIMARY KEY (id)
) WITH (OIDS=FALSE);
